
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jul 23 22:40:57 CDT 2021
//----------------------------------------------------

package fes.aragon.compilador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 5;
  public static final int TRUE = 2;
  public static final int EOF = 0;
  public static final int ASIG = 9;
  public static final int FALSE = 3;
  public static final int ID = 11;
  public static final int error = 1;
  public static final int RPAREN = 8;
  public static final int PUNTOYCOMA = 10;
  public static final int NOT = 4;
  public static final int LPAREN = 7;
  public static final int OR = 6;
}

